/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

/**
 *
 * @author magno-trabalho
 */
public class PrincipalAdmin extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalAdmin
     */
    public PrincipalAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmUsuarios = new javax.swing.JMenu();
        jmClientes = new javax.swing.JMenu();
        jmtListarClientes = new javax.swing.JMenuItem();
        jmtAddClientes = new javax.swing.JMenuItem();
        jmAdmin = new javax.swing.JMenu();
        jmListarAdmin = new javax.swing.JMenuItem();
        jmAddAdmin = new javax.swing.JMenuItem();
        jmBiblioteca = new javax.swing.JMenu();
        jmFilmes = new javax.swing.JMenu();
        jmListarFilmes = new javax.swing.JMenuItem();
        jmAddFilme = new javax.swing.JMenuItem();
        jmSeries = new javax.swing.JMenu();
        jmListarSerie = new javax.swing.JMenuItem();
        jmAddSeries = new javax.swing.JMenuItem();
        jmMusicas = new javax.swing.JMenu();
        jmListarMusicas = new javax.swing.JMenuItem();
        jmAddMusicas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela do Administrador");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        jLabel1.setText("Seria Melhor fazer em PHP");
        jLabel1.setAutoscrolls(true);

        jmUsuarios.setText("Usuarios");

        jmClientes.setText("Clientes");

        jmtListarClientes.setText("Listar");
        jmtListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmtListarClientesActionPerformed(evt);
            }
        });
        jmClientes.add(jmtListarClientes);

        jmtAddClientes.setText("Adicionar");
        jmtAddClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmtAddClientesActionPerformed(evt);
            }
        });
        jmClientes.add(jmtAddClientes);

        jmUsuarios.add(jmClientes);

        jmAdmin.setText("Administrador");

        jmListarAdmin.setText("Listar");
        jmListarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmListarAdminActionPerformed(evt);
            }
        });
        jmAdmin.add(jmListarAdmin);

        jmAddAdmin.setText("Adicionar");
        jmAddAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAddAdminActionPerformed(evt);
            }
        });
        jmAdmin.add(jmAddAdmin);

        jmUsuarios.add(jmAdmin);

        jMenuBar1.add(jmUsuarios);

        jmBiblioteca.setText("Biblioteca");

        jmFilmes.setText("Filmes");

        jmListarFilmes.setText("Listar");
        jmListarFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmListarFilmesActionPerformed(evt);
            }
        });
        jmFilmes.add(jmListarFilmes);

        jmAddFilme.setText("Adicionar");
        jmAddFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAddFilmeActionPerformed(evt);
            }
        });
        jmFilmes.add(jmAddFilme);

        jmBiblioteca.add(jmFilmes);

        jmSeries.setText("Series");

        jmListarSerie.setText("Listar");
        jmListarSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmListarSerieActionPerformed(evt);
            }
        });
        jmSeries.add(jmListarSerie);

        jmAddSeries.setText("Adicionar");
        jmAddSeries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAddSeriesActionPerformed(evt);
            }
        });
        jmSeries.add(jmAddSeries);

        jmBiblioteca.add(jmSeries);

        jmMusicas.setText("Musicas");

        jmListarMusicas.setText("Listar");
        jmListarMusicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmListarMusicasActionPerformed(evt);
            }
        });
        jmMusicas.add(jmListarMusicas);

        jmAddMusicas.setText("Adicionar");
        jmAddMusicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAddMusicasActionPerformed(evt);
            }
        });
        jmMusicas.add(jmAddMusicas);

        jmBiblioteca.add(jmMusicas);

        jMenuBar1.add(jmBiblioteca);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(394, 394, 394)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(623, 623, 623))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(222, 222, 222))
        );

        setSize(new java.awt.Dimension(1210, 630));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmAddSeriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAddSeriesActionPerformed
        JDCadastroSerie subtela = new JDCadastroSerie(this, true);
        subtela.setVisible(true);
    }//GEN-LAST:event_jmAddSeriesActionPerformed

    private void jmtListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmtListarClientesActionPerformed
        JDListaCliente subtela = new JDListaCliente(this, true);
        subtela.setVisible(true);
    }//GEN-LAST:event_jmtListarClientesActionPerformed

    private void jmtAddClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmtAddClientesActionPerformed
        JDCadastroCliente subtela = new JDCadastroCliente(this, true);
        subtela.setVisible(true);
    }//GEN-LAST:event_jmtAddClientesActionPerformed

    private void jmListarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmListarAdminActionPerformed
        JDListaAdmin subtela = new JDListaAdmin(this, true);
        subtela.setVisible(true);
    }//GEN-LAST:event_jmListarAdminActionPerformed

    private void jmAddAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAddAdminActionPerformed
        JDCadastroAdmin subtela = new JDCadastroAdmin(this, true);
        subtela.setVisible(true);
    }//GEN-LAST:event_jmAddAdminActionPerformed

    private void jmListarFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmListarFilmesActionPerformed
        JDListaFilme subtela = new JDListaFilme(this, true);
        subtela.setVisible(true);
    }//GEN-LAST:event_jmListarFilmesActionPerformed

    private void jmListarSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmListarSerieActionPerformed
        JDListaSerie subtela = new JDListaSerie(this, true);
        subtela.setVisible(true);
    }//GEN-LAST:event_jmListarSerieActionPerformed

    private void jmListarMusicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmListarMusicasActionPerformed
        JDListaMusica subtela = new JDListaMusica(this, true);
        subtela.setVisible(true);
    }//GEN-LAST:event_jmListarMusicasActionPerformed

    private void jmAddFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAddFilmeActionPerformed
        JDCadastroFilme subtela = new JDCadastroFilme(this, true);
        subtela.setVisible(true);
    }//GEN-LAST:event_jmAddFilmeActionPerformed

    private void jmAddMusicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAddMusicasActionPerformed
        JDCadastroMusica subtela = new JDCadastroMusica(this, true);
        subtela.setVisible(true);
    }//GEN-LAST:event_jmAddMusicasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmAddAdmin;
    private javax.swing.JMenuItem jmAddFilme;
    private javax.swing.JMenuItem jmAddMusicas;
    private javax.swing.JMenuItem jmAddSeries;
    private javax.swing.JMenu jmAdmin;
    private javax.swing.JMenu jmBiblioteca;
    private javax.swing.JMenu jmClientes;
    private javax.swing.JMenu jmFilmes;
    private javax.swing.JMenuItem jmListarAdmin;
    private javax.swing.JMenuItem jmListarFilmes;
    private javax.swing.JMenuItem jmListarMusicas;
    private javax.swing.JMenuItem jmListarSerie;
    private javax.swing.JMenu jmMusicas;
    private javax.swing.JMenu jmSeries;
    private javax.swing.JMenu jmUsuarios;
    private javax.swing.JMenuItem jmtAddClientes;
    private javax.swing.JMenuItem jmtListarClientes;
    // End of variables declaration//GEN-END:variables
}
